CREATE TABLE public.assets (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	description varchar NOT NULL,
	model varchar NOT NULL,
	health_level numeric NOT NULL,
	"status" varchar NOT NULL,
	"owner" int4 NOT NULL,
	CONSTRAINT assets_pkey PRIMARY KEY (id)
);

CREATE TABLE public.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar NOT NULL,
	"name" varchar NOT NULL,
	"password" varchar NOT NULL,
	username varchar NOT NULL,
	company_id int4 NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.units (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	company_id int4 NOT NULL,
	CONSTRAINT units_pkey PRIMARY KEY (id)
);

ALTER TABLE public.assets ADD CONSTRAINT assets_fk FOREIGN KEY (owner) REFERENCES units(id) ON DELETE CASCADE;

CREATE TABLE public.companies (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NULL,
	CONSTRAINT companies_pkey PRIMARY KEY (id)
);

ALTER TABLE public.units ADD CONSTRAINT company_fk FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE;
ALTER TABLE public.users ADD CONSTRAINT company_fk FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE;


